### ISSUE TITLE
add lerc benchmarks near the top of the readme

### ISSUE THREAD

**Issue by jgravois** [Esri/lerc#11]
presenting a chart demonstrating some benchmarks would be an *extremely* valuable way to put a point on what the format is all about in a succinct way.

**Comment by tmaurer3** [comment]
John,

It is not that simple and can’t be done with just a little table. I can email you a 10 page document with older, outdated benchmarks to give you an idea.

The compression depends on the data, the data type, whether compression is lossless or lossy, and very strongly on the parameter MaxZError. By increasing this parameter, Lerc can achieve ANY compression factor. It is up to the user which precision he needs or which max compression error per pixel he can live with. And for most of this, there is no other compression method to compare to.

For integer data types such as satellite images, one could compare Lerc lossless against other lossless methods such as png, LZW, jpeg2000. Traditional compression methods are highly optimized for 8 bit data, so here Lerc can only get close but not beat them. The more bits per pixel, the better Lerc comes out in comparison. At 16 bit Lerc can beat png. It beats LZW most of the time. Not jpeg2000, but that is extremely slow so people don’t like it much.

What I haven’t even mentioned yet is that most compression methods have their own parameters you can set and vary. Often a tradeoff between higher compression versus higher speed.

Comparing speed. Lerc runs entirely in memory. There is no file IO, and it is often used like that. For a fair comparison against other formats, you cannot just call jpeg encode and decode functions that write and read the jpeg compressed image to and from the hard drive. One would have to write custom test code that does the jpeg compression in memory, use a RAM disk, or similar tricks.

Now, the Lerc API allows you to easily Lerc encode and decode your own images of whatever data type, band number, and size. The Lerc test program measures the compression achieved, and the cpu time needed for both encode and decode.

Best, Thomas.


presenting a chart demonstrating some benchmarks would be an extremely valuable way to put a point on what the format is all about in a succinct way.

**Comment by jgravois** [comment]
@ajturner i'd be **so** curious to hear your thoughts here.  i absolutely grant that *its complicated* is a fair answer, but i think its **crucial** that we try to boil down the capabilities of the format into a digestible chart (and make sure to be honest about the fact that distillation is inherently subjective).

i know there are some older benchmarks floating around somewhere.  it'd be a great start to recompress and get hard numbers demonstrating the performance improvements.

**Comment by jgravois** [comment]
closed via 418bd19
