### ISSUE TITLE
Question: what should be the official name of libs files?

### ISSUE THREAD

**Issue by SpaceIm** [Esri/lerc#125]
I'm creating a recipe of lerc for conan: https://github.com/conan-io/conan-center-index/pull/1159

It's not really clear what names should be given to generated lib files: LercLib (in CMakeLists in master)? Lerc (in bin)?

By the way, why do you force using shared lib in build scripts? Seems to also properly work as static lib.

For example, here is how I've patched v2.1 for conan in order to support static or shared, but also to quickly fix strange things in macros related to LERCDLL_API:

```patch
--- /dev/null
+++ b/CMakeLists.txt
@@ -0,0 +1,24 @@
+cmake_minimum_required(VERSION 3.0.2)
+project(Lerc)
+
+file(GLOB SOURCES 
+  "src/LercLib/*"
+  "src/LercLib/Lerc1Decode/*"
+)
+
+add_library(LercLib ${SOURCES})
+set_property(TARGET LercLib PROPERTY CXX_STANDARD 11)
+if(BUILD_SHARED_LIBS)
+  set_property(TARGET LercLib PROPERTY CXX_VISIBILITY_PRESET hidden)
+  if(WIN32)
+    target_compile_definitions(LercLib PRIVATE LERC_EXPORTS)
+  endif()
+endif()
+
+set(HEADER_FILES include/Lerc_c_api.h include/Lerc_types.h)
+install(FILES ${HEADER_FILES} DESTINATION include)
+install(TARGETS LercLib
+  RUNTIME DESTINATION bin
+  LIBRARY DESTINATION lib
+  ARCHIVE DESTINATION lib
+)
--- a/include/Lerc_c_api.h
+++ b/include/Lerc_c_api.h
@@ -28,13 +28,7 @@ Contributors:  Thomas Maurer
 extern "C" {
 #endif
 
-#if defined(_MSC_VER)
-  #define LERCDLL_API __declspec(dllexport)
-#elif __GNUC__ >= 4
-  #define LERCDLL_API __attribute__((visibility("default")))
-#else
-  #define LERCDLL_API
-#endif
+#define LERCDLL_API
 
 
   //! C-API for LERC library
--- a/src/LercLib/Lerc_c_api.h
+++ b/src/LercLib/Lerc_c_api.h
@@ -28,8 +28,12 @@ Contributors:  Thomas Maurer
 extern "C" {
 #endif
 
-#if defined(_MSC_VER)
-  #define LERCDLL_API __declspec(dllexport)
+#ifdef _WIN32
+  #ifdef LERC_EXPORTS
+    #define LERCDLL_API __declspec(dllexport)
+  #else
+    #define LERCDLL_API
+  #endif
 #elif __GNUC__ >= 4
   #define LERCDLL_API __attribute__((visibility("default")))
 #else
```

**Comment by tmaurer3** [comment]
@SpaceIm  Sorry for the late reply. I had no strong opinion on the name, Lerc.dll or LercLib.dll. Just today I merged the cmake updates by another user who is also leaning towards the first. 
Feel free to create a PR for this, ideally with Lerc as the target name, and so it fits well with your Conan package. Or how big of a problem is it to change that name?

**Comment by tmaurer3** [comment]
@SpaceIm The preferred name is "Lerc.dll". Closing this issue.

**Comment by SpaceIm** [comment]
Ok, so current CMakeLists doesn't honor this name.

**Comment by tmaurer3** [comment]
@SpaceIm  So we replace "LercLib" by "Lerc" in 3 places? Then we are good?
