### ISSUE TITLE
Doc on how to compile Lerc on different platforms

### ISSUE THREAD

**Issue by andr7430** [Esri/lerc#13]
I think it would be great if we can have some documentation on how to compile Lerc on Linux or OSX. Such as whether there are any special libraries that I need to install. 

Also, I assume we can't run LercTest on OSX because of PerfTimer?

**Comment by tmaurer3** [comment]
The Lerc API is pure stand-alone C++, no dependencies.

The PerfTimer in the test program is windows only. If you compile on Linux or else, comment it out. Makefiles for Linux and others will come. If you want to create it, great, I will gladly add them. And I don’t expect it to be hard. The Lerc API is one single dll with no dependencies. The test app is small and basic as well.

**Comment by jgravois** [comment]
thanks @andr7430 for the suggestions.  any help you can provide to make the repo more cross platform would be super helpful.

**Comment by tmaurer3** [comment]
Added build instructions for Windows and Linux. Closing this issue.
