### ISSUE TITLE
Pixel-interleaved output in JS

### ISSUE THREAD

**Issue by zakjan** [Esri/lerc#146]
This is a general question: Is it intentional that JS decompression output is always band-interleaved, even though C++/GDAL compression input is pixel-interleaved?

Currently I had to transform from band-interleaved to pixel-interleaved if expected by geotiff.js:

https://github.com/geotiffjs/geotiff.js/blob/5816200dfb610ef11b1de9e09b214175739e9e90/src/compression/lerc.js#L40

**Comment by tmaurer3** [comment]
@zakjan  Lerc allows for both at the same time. If you look at the API, besides nCols and nRows, there is both nBands and nDim (which I plan to rename to nDepth at some point). You can have 4 dimensions. E.g., for nDim = 5 and nBands = 3, you can store 5 values per pixel and do this for 3 bands. 

As long as you encode the data, the choice is yours. However, for a general decoder, it must deal with all combinations. If a Lerc decoder requires nDim or nBands to be 1, that is a bug. These parameters nBands and nDim should not be understood as an interleave flag. Lerc is already used to store multi-dimensional raster data with both parameters > 1.

**Comment by zakjan** [comment]
Ok, does it mean that the presence of nDim > 1 in encoded header should always be interpreted as pixel-interleaved by decoder?

However, constructConstantSurface always iterates over nDims * pixels. I can't see that it would iterate over pixels * nDims.

https://github.com/Esri/lerc/blob/3f523fee2b5764f2029e035c41a2325b6360a29d/OtherLanguages/js/LercDecode.js#L1644-L1652

Also, nBands > 1 is supposed to be stored as separate LERC blocks? When I stepped through the code, I found out that data are always stored in a single LERC block in all cases that I tried. While until eof iteration always ran only one iteration.

https://github.com/Esri/lerc/blob/3f523fee2b5764f2029e035c41a2325b6360a29d/OtherLanguages/js/LercDecode.js#L2124

Sample files generated with GDAL attached. (1 band-interleaved file, 1 pixel-interleaved file, both with 5 constant bands)

[Archive.zip](https://github.com/Esri/lerc/files/6267802/Archive.zip)

**Comment by tmaurer3** [comment]
@zakjan  Short answer: I agree with you. The JS decoder should return the data values as is and without rearranging them. 

@zakjan @rouault @lucianpls @wju  Longer answer (guys cc'd feel free to chime in and correct me here): 

_ Yes, Lerc stores each band in its own tile with Lerc tile header. Multiple bands can be stored by concatenating such single band blobs. The JS decoder keeps reading such band blobs until eof. 

_ Tiff in GDAL apparently does not use that. It does not care about 4 dimensional data, just 2D + nBands. It uses Lerc's nDim feature for pixel interleaved. I'm not sure how it stores band interleaved using Lerc, but apparently into a single band Lerc blob somehow. Meaning you never see the concatenated Lerc blob version coming out of Tiff / GDAL. 

_ MRF (Meta Raster Format), also in GDAL, manages the bands above Lerc. It only uses Lerc per band. The advantage: Caller can decode a single band (say band 8) without having to decode all the other bands before that. 

_ CRF (Cloud Raster Format), not in GDAL, but heavily used at Esri, also for image services and in the cloud, uses Lerc also for 4 dimensional data. It does concatenate the Lerc blobs for multiple bands if needed. 

_ The JS Lerc decoder not only tries to decode any encoded Lerc blob but also is used to directly render this data in the browser. I guess that it encountered pixel interleaved Lerc blobs like the ones created in Tiff / GDAL and converted this to band interleaved so it displays in the browser. 

I think the proper solution is to have the JS Lerc decoder decode the Lerc blob without doing any conversion or data rearrangement, by default. If it has to convert the data from pixel interleaved to band interleaved for rendering, that should be controlled by an extra flag.

**Comment by lucianpls** [comment]
@tmaurer3
_MRF (Meta Raster Format).  It is using nDim for pixel interleaved, same as Tiff, since Aug 2020

**Comment by wju** [comment]
For MRF, I didn't have problems to read it using the JS Lerc Decoder, probably because I never tried a pixel interleaved MRF test case. All the test cases I have are encoded per band, each band has its own offset and size stored in the index file. @lucianpls I'll ask Abhijit for more data.

For TIFF, I encountered similar issues as @zakjan but I was using a much older GDAL (v2.3.3) --- our older Optimized Raster workflow used that version. Because it's too early I didn't pursue a solution. Looks like it's finalized now.

Now we have both TIFF and MRF formats that use ```dimensions``` for BIP layout, and our internal raster API also have problems to read them. I'm planning to resolve it in our next release cycle. Since the information is at the raster format level, we'll need to expose optional BIP/BSQ flags as @tmaurer3 suggested.

https://github.com/Esri/lerc/blob/5373bb56386ea6f6261090137ebfc9e667c633f0/OtherLanguages/js/LercDecode.js#L1900-L1908

Did a quick experiment today, looks promising -- I can read my old TIFF and the two TIFFs provided by @zakjan. Once we complete development and testing, we'll make the JS update to this repo.

**Comment by zakjan** [comment]
Thanks @tmaurer3 @wju for your detailed answers.

Regarding GeoTIFF / MRF, right, band-interleaved GeoTIFF stores bands separate, having the same advantage as band-interleaved MRF. There is no 4D support as far as I know.

Explicit 4D support in CRF / LERC is interesting. However, because of how LERC works, I suppose there is no compression improvement over 3D? The advantage is probably only optimizing the storage layout for further processing?

An extra flag for controlling the output format (keep original by default) would be great to have.

**Comment by zakjan** [comment]
@wju @tmaurer3 Thanks! Would you mind to add the new option to readme, and release it to npm, so that it's possible to use it as a dependency in geotiff.js?
