### ISSUE TITLE
Would be helpful to be able to make static libs

### ISSUE THREAD

**Issue by lgritz** [Esri/lerc#158]
It would be very helpful if the CMakeLists.txt, instead of hard-coding `SHARED` on the add_library command, instead honored the standard convention of using an option BUILD_SHARED_LIBRARIES (the default can be ON). This would allow a user/site to easily override the default in order to build static libraries if they need it.

The idiom for doing this is simply:

    # Make an option, defaulting to shared libs, but allow -DBUILD_SHARED_LIBS=OFF
    option (BUILD_SHARED_LIBS "Build shared libraries (set to OFF to build static libs)" ON)

    # If no SHARED or STATIC is specified explicitly, add_library will honor BUILD_SHARED_LIBS
    add_library (mylibrary ${SOURCES})

I'm sorry I have to just leave these breadcrumbs at your door instead of submitting a proper PR that fully implements it. There's too much bureaucracy in my organization to get legal approval for a one-time, two-line patch.

Thanks for your work with this library!

**Comment by tmaurer3** [comment]
@lgritz  No problem, improvements are always welcome! Thanks!

**Comment by Biswa96** [comment]
I have fixed some issues with static library. Please see the linked pull request above. To enable static linking, you have to define `LERC_STATIC` symbol or add `-DLERC_STATIC` to CPPFLAGS or use the output of `pkg-config -cflags -static lerc` command. Please let me know if there is any issue. I would be happy to help anytime.
