### ISSUE TITLE
how to write lerc byte lerc data to file 

### ISSUE THREAD

**Issue by lzxue** [Esri/lerc#19]
the  doc not Introduction how  write the compress result  to file and the lerc data structure. 

I have write the pLercBlob to file，but the lerc file need the header,
the code 
` for(int i=0;i<numBytesBlob;i++)
    
  outfile.write((char*)&pLercBlob[i],sizeof(pLercBlob[i]));

outfile.close( ); `

**Comment by tmaurer3** [comment]
The Lerc byte blob already contains the header. You can write out the Lerc byte blob in one line using fwrite. See, e.g.
http://www.cplusplus.com/reference/cstdio/fwrite/

When reading it back in, use fread. See 
https://github.com/Esri/lerc/blob/master/src/LercTest/main.cpp

fread(pLercBuffer, 1, fileSize, fp);    // read Lerc blob into buffer

**Comment by lzxue** [comment]
Thanks for you answer
now ,i can't solve this question
The following code  base on https://github.com/Esri/lerc/blob/master/src/LercTest/main.cpp
    
     if(!lerc.Encode((void*)zImg,    // raw image data, row by row, band by band
    
     Lerc::DT_Float,
    w, h, 1,
    &bitMask,           // 0 if all pixels are valid
    maxZError,           // max coding error per pixel, or precision
    pLercBlob,           // buffer to write to, function will fail if buffer too small
    numBytesBlob,        // buffer size
    numBytesWritten))    // num bytes written to buffer
    {
    cout << "Encode failed" << endl;
     }
    FILE * pFile;
    pFile = fopen ("/myfile.lerc", "wb");
    fwrite (*pLercBlob, sizeof(Byte), numBytesBlob, pFile);
    fclose (pFile);
  
but the result is wrong，i'm not a c++  programmer，can you help me

**Comment by tmaurer3** [comment]
fwrite(pLercBlob, ... )
Why don't you do a C++ class first and then come back to this? You will find Lerc easy to use once you know some basic C++.

**Comment by zxwandrew** [comment]
@lzxue  
It is common to overlook little things like this. Since the first parameter of fwrite takes a pointer to an array of elements, you can pass pLercBlob directly to it, because pLercBlob is already a pointer of the type Byte. 
There is no need to dereference by adding * in front of it.

The following line is enough as mentioned by tmaurer3 
fwrite (pLercBlob, sizeof(Byte), numBytesBlob, pFile);

**Comment by lzxue** [comment]
use gdal2.1 generate the mrf file 
 
   gdal_translate -of MRF -co COMPRESS=LERC  ASTGTM2_N30E112/ASTGTM2_N30E112_dem.tif      out.mrf

why the lercodec.py can’t read it

**Comment by lucianpls** [comment]
Because by default MRF generates LERC V2 and the python decoder can only read LERC V1 at the moment.  To generate LERC V1 with gdal use:

gdal_translate -of MRF -co COMPRESS=LERC -co OPTIONS="V1:ON" input.file out.mrf

**Comment by lzxue** [comment]
i have test all the way to generates Lerc v1，such as the lerc source code and gdal-transate ,but  i find the result  different  with the .lerc  (https://github.com/Esri/lerc/blob/master/py/world.lerc)  data .it can't use the py or js to read

**Comment by lucianpls** [comment]
Not easily.
You should be able to write an MRF that contains a single tile, by using -co BLOCKXSIZE=<xsize> -co BLOCKYSIZE=<ysize> in the gdal_translate command line.  Then the MRF data file (the .lrc) will be a single Lerc blob.
