### ISSUE TITLE
Unable to static link lerc on Windows OOTB

### ISSUE THREAD

**Issue by Arignir** [Esri/lerc#192]
Hello,

One of my project is using lerc as a sub-sub dependency and I am currently unable to link it on Windows (using msys2 and MINGW) because apparently lerc doesn't provide an out-of-the-box solution to build a static library for Windows.

I've opened [an issue](https://github.com/msys2/MINGW-packages/issues/10268) on msys2's MinGW package repository where people are already talking about potential solutions: most of them consist of providing a way to define `LERCDLL_API` to nothing.

Thank you for your time and your help,
Arignir

**Comment by tmaurer3** [comment]
@Arignir  So does this fix work for you?

**Comment by Biswa96** [comment]
I have fixed some issues with static library. Please see the linked pull request above. To enable static linking, you have to define `LERC_STATIC` symbol or add `-DLERC_STATIC` to CPPFLAGS or use the output of `pkg-config -cflags -static lerc` command. Please let me know if there is any issue. I would be happy to help anytime. /cc @kmilos
