### ISSUE TITLE
Doc question: How are void pixels handled?

### ISSUE THREAD

**Issue by kannes** [Esri/lerc#195]
I am currently reading through the patent and have a question (probably stupid and there are probably more to come :D ). I hope it is ok if I use an issue here for this.

A LERC block knows about the number of valid/non-negative pixels and then there is the bitstuffed data (which can be unpacked since we know the bits per pixel and the number of pixels). But there could be "void" pixels (~=NODATA pixels).

Looking at https://raw.githubusercontent.com/Esri/lerc/master/doc/LercEncodingSample.png there are four "void" pixels.

What happens with them when encoding? How would I know where to re-insert them in the block when unpacking if I just find 12 pixel values for the 4x4 (=16 pixels) block?

**Comment by tmaurer3** [comment]
@kannes  No problem. Both during encode and decode, it uses the bit mask that tells which pixel is valid / invalid. For decode, see https://github.com/Esri/lerc/blob/master/src/LercLib/Lerc2.cpp#L1983 . Here, it would go over the 12 valid values, and assign them to the valid pixels. The void pixels are skipped. The order in which it goes over the pixels is fixed. The bit mask is encoded before the pixel values in the Lerc blob and read before the pixel values.

**Comment by kannes** [comment]
Thank you very much, that makes a lot of sense now :)
