### ISSUE TITLE
Suggestion: utilize git 'releases' and maintain a changelog

### ISSUE THREAD

**Issue by jgravois** [Esri/lerc#21]
the readme for this project mentions that the version is now at `Lerc2 v3`.  i recommend the following:
1. take advantage of git/github tags and [releases](https://help.github.com/articles/creating-releases/)
2. maintain a [Changelog.md](http://keepachangelog.com/)
3. use [Semantic Versioning](http://semver.org/) to denote breaking changes and other alterations to the code.

doing this would give outside developers a much better understanding of what is going on with the project.

**Comment by tmaurer3** [comment]
This Lerc repo has no official release tag yet. Reason is it is ahead of the Lerc versions used inside Esri ArcMap and Esri Pro, and we want to sync it all up first. Already ArcMap 10.4.1 and Pro 1.3 can read the current Lerc2 v3. But not write. The next Esri releases ArcMap 10.5 and Pro 1.4 should be fully in sync with this Lerc repo. This should happen in second half of 2016. Then we plan to tag this Lerc repo with a release tag of 1.0.

**Comment by jgravois** [comment]
https://github.com/Esri/lerc/releases/tag/v1.0

looks great!
