### ISSUE TITLE
Typescript export interfaces

### ISSUE THREAD

**Issue by Radik24** [Esri/lerc#217]
Hi,

is I just installed `4.0.0.`, but I cannot import interfaces from your library. Can you please export those interfaces?

Thanks you

**Comment by wju** [comment]
The update has been published to [npm](https://www.npmjs.com/package/lerc/v/4.0.1), fyi @Radik24 
cc @tmaurer3

**Comment by Radik24** [comment]
Thank you! @wju @tmaurer3
