### ISSUE TITLE
Is it possible to encode a multi-band image service in one LERC blob?

### ISSUE THREAD

**Issue by mappingvermont** [Esri/lerc#22]
I'm using the `Composite Bands` python raster function to combine three mosaic datasets into one image service. I'm publishing this service using LERC tiles that are generated on the fly. 

I'm reading the tiles using [this example](https://github.com/Esri/lerc/blob/master/js/index.htm) from @jgravois, When I log the pixel values, however, I'm only getting data from the first raster, not all three. 

Is it possible to encode a multi-band image service in LERC using out of the box ArcGIS Server 10.3? For more information, see my [Stack Exchange post](http://gis.stackexchange.com/questions/194059/arcgis-image-service-multiband-raster-in-lerc-tiles).

Apologies if this is the wrong location to post this. Thanks!

**Comment by lucianpls** [comment]
It is probably more of a limitation of the JS decoder and the test viewer, which were only used for single band.  
A multi-band LERC has a first blob that contains the data mask and the first band, immediately followed by LERC blobs for each extra band, but without the mask.  You are supposed to reuse the mask from the first band.
With the JS decoder, you would need to somehow keep track of how many bytes have been used, test that there is another LERC blob in the original tile and call the JS decoder again, for each extra band.

**Comment by mappingvermont** [comment]
Thanks so much for your response @lucianpls. 

I don't have much javascript experience, and am new to codecs-- is there anywhere in  [LercCodec.js](https://github.com/Esri/lerc/blob/master/js/LercCodec.js) you can point to that might help me detect the existence of another LERC blob?

Or is there someone else I can follow up with to get more information? Thanks!

**Comment by lucianpls** [comment]
I'm a beginner myself at JS, but reading the comments from the LercCodec.js:
If you call the LercCodec with returnFileInfo = true and returnMask = true, it will return a fileInfo structure and the mask.
The returned fileInfo.fp is the size of the decoded part.  If that figure is smaller than the input size, call LercCodec on the input again with inputOffset = fileInfo.fp and the encodedMask returned from the first call.

**Comment by mappingvermont** [comment]
Great-- that gives me a good start. I'll report back here after I've worked on this a little bit. Thanks!

**Comment by wju** [comment]
@mappingvermont 
The current js decoder does the bare minimum. To decode a multi-band pixel block, client needs to keep decoding until it reaches the end of the stream. We're planning to make this out of the box when lerc2 v3 JS decoder is available. 

I just uploaded a wrapper function to the js-lerc2 branch. The updated sample index.htm in js-lerc2 branch now supports any band (it draws the first three for multispectral data). There is a sample request you can use:
http://sampleserver6.arcgisonline.com/arcgis/rest/services/Toronto/ImageServer/exportImage?bbox=-8844874.0651,5401062.402699997,-8828990.0651,5420947.402699997&bboxSR=&size=&imageSR=&time=&format=lerc&pixelType=UNKNOWN&noData=&noDataInterpretation=esriNoDataMatchAny&interpolation= RSP_BilinearInterpolation&compression=&compressionQuality=&bandIds=&mosaicRule=&renderingRule=&f=image

**Comment by mappingvermont** [comment]
@wju Thanks so much! I'll try this out tomorrow!

**Comment by mappingvermont** [comment]
@wju Works like a charm! Thanks so much!!

**Comment by mappingvermont** [comment]
@wju and @lucianpls: do you have any idea when it will be possible to serve three band LERC tiles? I seem to be unable to do so from ArcMap 10.3/ArcGIS Server 10.3. 

I'm able to encode a three band image service in LERC (as in your example above), but when I try to enable caching for this service, LERC is not among the options in the dropdown.

See my [Stack Exchange post](http://gis.stackexchange.com/questions/194195/publishing-a-three-band-arcgis-imageservice-and-encoding-tiles-with-lerc) for more information. Any idea when this will be available?

**Comment by wju** [comment]
@mappingvermont It's definitely something very nice and important to have. We're considering to support it in 10.5.

**Comment by mappingvermont** [comment]
Thanks so much @wju. Just wanted to be sure I wasn't missing something! I hope you folks implement this in 10.5!

**Comment by wju** [comment]
@mappingvermont We had to defer general lerc/lerc2 tile service REST API due to its complexity (server, desktop/js/runtime clients, etc.), it remains on the radar of future developments. However, we managed to support lerc2 in image service exportImage operation at 10.5 (via a new flag lercVersion=2). The js decoder was also updated to support lerc2. The RasterLayer in the upcoming ArcGIS JS API will also use lerc2 by default. 
If your project requires a tile behavior, you can still achieve it by using a workaround:   construct a tiling scheme on client side, translate the corresponding level/row/col to equivalent bbox in exportImage requests. The Image service dynamic processing is pretty efficient in this case and also implements standard cache-control headers, so browser client can hardly feel slowness given other overhead (http traffic, decode, client side rendering etc.) --- a lot of coding though, have fun :)

**Comment by mappingvermont** [comment]
**@wju** thanks for keeping me up to date! Will let you know if I end up using this approach. Thanks!
