### ISSUE TITLE
Support for big-endian architectures

### ISSUE THREAD

**Issue by avalentino** [Esri/lerc#220]
Feature request: please consider to support also big endian architectures.

**Comment by tmaurer3** [comment]
@avalentino  Sorry for the late reply. I have been thinking about it, and asked others for their opinion, too. My impression is there is no strong demand for it. It says in https://en.wikipedia.org/wiki/Endianness: "little endian is the dominant ordering for processor architectures". Many newer processors also support bi-endian, they can switch. My impression is that the overall share of big endian only processors continues to decline. 
Adding big endian support to Lerc would mean bloating the code with swap commands, plus other changes. It would make life somewhat harder for everyone who wants to extend or modify the code. So at this point I'm leaning toward leaving it as is.

**Comment by gsteemso** [comment]
I thought about this, and I believe there are two approaches to supporting big-endian processors, only one of which suffers from the problems you note.  The cheap and simple way to do it is to declare by fiat that, while the standard interchange format for Lerc data shall be little-endian, implementations are free to use big-endian data internally.  While I have not had time to peruse Lerc’s actual code, in my experience, even arbitrary bit-field data tends to be processed at some level in multi-byte units of standardized size.  These units of standardized size - usually 32 or 64 bits, these days - behave predictably regardless of the order their constituent bytes are stored in.  Assuming nothing super esoteric is going on, it should be possible to compile Lerc almost as-is on a big-endian machine and have it behave in an _internally consistent_ manner; once that milestone is achieved, allowing such a build to interact usefully with the little-endian majority is just a matter of inserting an I/O filter function to byte-reverse the individual fields in each blob if the code is run on a big-endian machine.  That doesn't require byte-swap operations strewn messily throughout the code, it just requires maintaining clarity of demarcation amongst the various data fields.  (By that I mean, shortcuts that make assumptions about adjacent data units may require extra analysis to ensure correct behaviour - but from a maintainability perspective, are such shortcuts really a good idea in the first place?)
