### ISSUE TITLE
BitStuffer2::BitStuff undefined bitshift

### ISSUE THREAD

**Issue by eslerm** [Esri/lerc#222]
In`BitStuffer2::BitStuff`, if `bitPos <= 0` and `(32 - bitPos >= numBits)` is `False`, an undefined bitshift will occur when [`(*srcPtr++) >> (32 - bitPos)`](https://github.com/Esri/lerc/blob/master/src/LercLib/BitStuffer2.cpp#L460).

LERC functions which use `BitStuff` make this scenario impossible by returning false if `numBits >= 32` before calling `BitStuff`. Users of the library may not do this. If that scenario is likely, could the `BitStuff` function be patched?

**Comment by tmaurer3** [comment]
@eslerm  No worries, BitStuff() is a private, low level member function of the BitStuffer2 class and can only be called from other class member functions. This function is at the very bottom of the boiler room. It is easier to understand once you know that it only gets called for (0 < numBits< 32). Bit stuffing integer numbers makes only sense inside this range. I have added more checks and comments so it is easier to see that this undefined bit shift cannot happen. I'd rather avoid putting asserts in the innermost loops. You can check out the updates to BitStuffer2.cpp at this PR: https://github.com/Esri/lerc/pull/224.

**Comment by eslerm** [comment]
Thanks for the explanation @tmaurer3!

Your PR looks great 😊

**Comment by setharnold** [comment]
+105 -206 *and* more checks in the right places! Nice :) Thanks
