### ISSUE TITLE
Lerc2 javascript reader

### ISSUE THREAD

**Issue by lovelypeople** [Esri/lerc#23]
We need to use lerc2 tile tool in our project but I can't find javascript reader for lerc2 (even in js-lerc2 branch), so I migrated C++ implementation to TypeScript on https://github.com/lovelypeople/lerc2-js, hope it can help.

**Comment by lucianpls** [comment]
Nice!  Thanks!

**Comment by wju** [comment]
Nice to hear that. We actually have a near-complete JS Lerc2 version that handles all minor versions and variations. It's not pushed up as we're waiting for some public accessible image services that use Lerc2. Let me talk to my colleagues and see if we can release it early. @lovelypeople

**Comment by lzxue** [comment]
hi,@wju  @lovelypeople is my colleagues ,we all the employee of GAGO .We have seen in the ESRI UI ,We look forward to your open source.

**Comment by wju** [comment]
@lzxue @lovelypeople aha, it's a small world 😄

**Comment by lovelypeople** [comment]
@wju Glad to see the official script 😄  .

**Comment by wju** [comment]
The LercCodec.js now handles all revisions of v2 as well. It's also amd loader friendly (dojo, requireJS). Lightly tested with a few manually cooked examples.

**Comment by lucianpls** [comment]
@wju Did you forget to push a commit?

**Comment by jgravois** [comment]
@lucian Wenxue pushed his new commit to a branch named [`js-lerc2`](https://github.com/Esri/lerc/tree/js-lerc2).

i already mentioned this in #18, but it would make this project substantially less opaque if we published the JavaScript decoder to `npm` so that it can be utilized conveniently both in Node.js and in the browser.  

i'd be more than happy to help w/ this if you want to tackle it and could use a hand.

**Comment by wju** [comment]
@jgravois @lucianpls Once fully tested, we can merge to master and create an npm package -- Yes please help @jgravois 👍

**Comment by jgravois** [comment]
i mocked up an npm package for `v1` here.  its written in ES6 and uses rollup to export a UMD module to ensure that the code can be easily ported to AMD, browserify, Node.js etc. etc.

https://github.com/jgravois/lerc/tree/npm-v1

**Comment by jgravois** [comment]
how that @wju's work has landed in `master` it should be safe to close this issue.

**Comment by wju** [comment]
:)
