### ISSUE TITLE
A different implementation for C♯

### ISSUE THREAD

**Issue by halmaia** [Esri/lerc#236]
Dear Thomas Maurer,

I checked the currently available implementation for C♯ (using the lib). I see, it was written in an older version of C♯. I have a couple of ideas to improve it.

1. In the current implementation DLLImport  and managed .NET arrays are used. With newer C♯ versions we can use Span<T> and ReadOnlySpan<T> types. In this case the user can pass arrays, spans, collections, C♯ safe and unsafe pointers, and even pointers coming from native environments and COM–being wrapped by a C♯ Span<T>. It would give some freedom for the user, without having the burden of marshalling, hence Spans are built around pointers (C♯ refs). In case of Spans the marshaling is just almost formal: the internal pointer will be published, no allocation & re-allocation needed. The length of Span is always stored, so they are safer than the standard pointers. With the help of ReadOnlySpan<T> you can mimic the C’s const void* behaviour. With Spans the user can pass arrays and spans whit implicit casting, even with reinterpret casting. The Spans will conform to the .NET original design goals (see FileStream’s Read function first argument).
2. It is possible to declare the external function as follows:
`[DllImport("Lerc.dll", EntryPoint = "lerc_computeCompressedSize", ExactSpelling = true)]
static extern unsafe ErrCode ComputeCompressedSize(void* pData, LercDataTypes dataType, int nDepth, int nCols, int nRows, int nBands, int nMasks, byte* pValidBytes, double maxZErr, uint* pNumBytes);`
In this case we won't let the .NET to do the marshalling for us and we can write a custom marshaller (see the example below.) It is also discouraged to publish externs as public, so it is declared private and called from a public function.
3. I also wrapped the extern calls into a function to check the results.

If you are not averse to having someone else in the repository, I would be happy to contribute in rewriting/creating a different wrapper for C♯.

Best regards,
Ákos Halmai

Here is the complete idea below. Maybe there are some overreactions in argument check, but the main idea is visible beginning at the first fixed keyword. Comments are mostly removed for brevity, but I left your original ones.

`    public static class LercCS
    {
        private const string dllName = @"Lerc.dll";
        public static unsafe uint ComputeCompressedSize(
         ReadOnlySpan<byte> Data,
         LercDataTypes DataType,
         int Depth,
         int Cols,
         int Rows,
         int Bands,
         int Masks,
         ReadOnlySpan<byte> ValidBytes,
         double MaxZErr = 0d)
        {
            
            GenericArgumentChecks(Depth, Cols, Rows, Bands, Masks);

            if (!(double.IsFinite(MaxZErr) && MaxZErr >= 0d))
                throw new ArgumentOutOfRangeException(nameof(MaxZErr));

            int exptectedNumberOfPixels = Cols * Rows,
                expectedNumberOfValues = exptectedNumberOfPixels * Bands,
                expectedNumberOfBytes = exptectedNumberOfPixels * Depth * DataType switch
                {
                    LercDataTypes.SByte or LercDataTypes.Byte => 1,
                    LercDataTypes.Short or LercDataTypes.UShort => 2,
                    LercDataTypes.Int or LercDataTypes.UInt or LercDataTypes.Float => 4,
                    LercDataTypes.Double => 8,
                    _ => throw new ArgumentOutOfRangeException(nameof(DataType))
                };

            if (Data.Length != expectedNumberOfBytes)
                throw new ArgumentOutOfRangeException(nameof(Data));

            int validBytesLength = ValidBytes.Length;

            if ((Masks is 1 && validBytesLength != exptectedNumberOfPixels) ||
                (Masks == Bands && validBytesLength != expectedNumberOfValues))
                throw new ArgumentOutOfRangeException(nameof(Masks));

            fixed (void* pData = &ReadOnlySpanMarshaller<byte, byte>.ManagedToUnmanagedIn.GetPinnableReference(Data))
            {
                Unsafe.SkipInit(out uint NumBytes);
                if (Masks is 0)
                    CheckStatus(ComputeCompressedSize(pData, DataType, Depth, Cols, Rows, Bands, Masks, null, MaxZErr, &NumBytes));
                else
                    fixed (byte* pValidBytes = &ReadOnlySpanMarshaller<byte, byte>.ManagedToUnmanagedIn.GetPinnableReference(ValidBytes))
                        CheckStatus(ComputeCompressedSize(pData, DataType, Depth, Cols, Rows, Bands, Masks, pValidBytes, MaxZErr, &NumBytes));

                return NumBytes;
            }

            // Local function
            [DllImport(dllName, EntryPoint = "lerc_computeCompressedSize", ExactSpelling = true, SetLastError = false)]
            static unsafe extern ErrCode ComputeCompressedSize(
                void* pData,                 // raw image data, row by row, band by band
                LercDataTypes dataType,             // char = 0, uchar = 1, short = 2, ushort = 3, int = 4, uint = 5, float = 6, double = 7
                 int nDepth,                        // number of values per pixel (e.g., 3 for RGB, data is stored as [RGB, RGB, ...])
                 int nCols,                         // number of columns
                 int nRows,                         // number of rows
                 int nBands,                        // number of bands (e.g., 3 for [RRRR ..., GGGG ..., BBBB ...])
                 int nMasks,                        // 0 - all valid, 1 - same mask for all bands, nBands - masks can differ between bands
                 byte* pValidBytes,  // nullptr if all pixels are valid; otherwise 1 byte per pixel (1 = valid, 0 = invalid)
                 double maxZErr,                    // max coding error per pixel, defines the precision
                 uint* pNumBytes);           // size of outgoing Lerc blob
        }

        private static void GenericArgumentChecks(int Depth, int Cols, int Rows, int Bands, int Masks)
        {
            ArgumentOutOfRangeException.ThrowIfLessThan(Depth, 1, nameof(Depth));
            ArgumentOutOfRangeException.ThrowIfLessThan(Cols, 1, nameof(Cols));
            ArgumentOutOfRangeException.ThrowIfLessThan(Rows, 1, nameof(Rows));
            ArgumentOutOfRangeException.ThrowIfLessThan(Bands, 1, nameof(Bands));

            if (!(Masks is 0 or 1 || Masks == Bands))
                throw new ArgumentOutOfRangeException(nameof(Masks));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void CheckStatus(ErrCode lercStatus)
        {
            if (lercStatus is ErrCode.Ok) return;
            throw new InvalidOperationException(lercStatus switch
            {
                ErrCode.Failed => "Operation failed.",
                ErrCode.BufferTooSmall => "The provided buffer is too small.",
                ErrCode.WrongParam => "Wrong parameters were provided",
                ErrCode.NaN => "NaN not supported.",
                _ => "" // Formal.
            });
        }

        public enum LercDataTypes : uint
        {
            SByte,
            Byte,
            Short,
            UShort,
            Int,
            UInt,
            Float,
            Double
        }

        public enum ErrCode : uint
        {
            Ok,
            Failed,
            WrongParam,
            BufferTooSmall,
            NaN,
            HasNoData
        }
    }`

**Comment by tmaurer3** [comment]
@halmaia  Sure, you are welcome! Do you also see a speed up from these changes, and if yes, how much? Why don't you provide your updated C# version as a branch, so we can test it. Then PR, and in. Thank you!
