### ISSUE TITLE
Javascript demo raster can get out of pan sync

### ISSUE THREAD

**Issue by ajturner** [Esri/lerc#6]
http://developers.arcgis.com/javascript/samples/layers_raster/

Filter down temperatures and then pan:

<img width="800" alt="raster_layer_with_pixel_filter" src="https://cloud.githubusercontent.com/assets/1218/12688708/dab03f32-c6a5-11e5-9fb7-3f4759dac682.png">

@jgravois @tmaurer3

**Comment by PBecker92373** [comment]
Andrew
Very cool!

_Peter

Sent from my iPad

On Jan 29, 2016, at 4:08 PM, Andrew Turner <notifications@github.com<mailto:notifications@github.com>> wrote:


http://developers.arcgis.com/javascript/samples/layers_raster/

Filter down temperatures and then pan:

[raster_layer_with_pixel_filter]<https://cloud.githubusercontent.com/assets/1218/12688708/dab03f32-c6a5-11e5-9fb7-3f4759dac682.png>

@jgravois<https://github.com/jgravois> @tmaurer3<https://github.com/tmaurer3>

-

**Comment by jgravois** [comment]
it seems like a fix for this is more likely to be in the JSAPI than in LERC itself.

do you agree @bsvensson? @wju?

**Comment by bsvensson** [comment]
> it seems like a fix for this is more likely to be in the JSAPI than in LERC itself.

I think it's more related to the specific sample.

**Comment by jgravois** [comment]
i'm not sure why anything should be required in an individual application to ensure that a [`RasterLayer`](https://developers.arcgis.com/javascript/jsapi/rasterlayer-amd.html) image stays in sync when the map is panned, but your hunches are usually better than mine.

**Comment by jgravois** [comment]
@ajturner, can you close this issue when you have a moment? @bsvensson and his team can check out the problem on their side.

**Comment by ajturner** [comment]
Closing - @jgravois or @bsvensson please add link to related issue and resolution in other project
