### ISSUE TITLE
showing elevation can survive map zoom but not pan

### ISSUE THREAD

**Issue by jgravois** [Esri/lerc#8]
thanks to @lucianpls, we now display elevation in meters appropriately when using the +/- zoom buttons and dragging a box to zoom in the leaflet sample, but once the map is panned by click dragging, either the elevation shows as undefined, or a value is displayed from an offset location.

**Comment by lucianpls** [comment]
Are you sure?  It works fine in Firefox as far as I can tell, it only
blinks to undefined until the data is refreshed, which is normal.

**Comment by jgravois** [comment]
i can reproduce the problem in both Chrome `47` and Firefox `43`.

1. launch http://esri.github.io/lerc/js/leaflet.html
2. place the mouse in the middle of the atlantic ocean (west of spain) and pan.
3. hover over spain and note that the elevation is `undefinedm`

**Comment by lucianpls** [comment]
Right, I mostly checked on western US.

**Comment by lucianpls** [comment]
Actually no, the gihub.io sample is from an older version of the source.
Check out the latest from Github, it should work.

**Comment by jgravois** [comment]
awesome.  now we just need to get the `gh-pages` branch of this repository in sync with `master`.  
if you guys want to give me push access to this repo i'd be able to help with it myself.
