### ISSUE TITLE
Alignment errors in GetLercInfo on 32-bit ARM

### ISSUE THREAD

**Issue by jonfetterdegges** [Esri/lerc#93]
We're using lerc on Android devices. We periodically see unaligned access errors on 32-bit devices (ABI armeabi-v7a) arising from the assignments

```c++
    int height = *((const int*)ptr);  ptr += sizeof(int);
    int width  = *((const int*)ptr);  ptr += sizeof(int);
    double maxZErrorInFile = *((const double*)ptr);
```

in `Lerc::GetLercInfo` lines 154-156. At the moment we are avoiding the errors by using memcpy instead of pointer casting:

```c++
    int height;
    memcpy(&height, ptr, sizeof(int));
    ptr += sizeof(int);
    int width;
    memcpy(&width, ptr, sizeof(int));
    ptr += sizeof(int);
    double maxZErrorInFile;
    memcpy(&maxZErrorInFile, ptr, sizeof(double));
```

Can you incorporate this as a fix? I can provide a pull request if you'd like.

**Comment by tmaurer3** [comment]
Fixed.

**Comment by jonfetterdegges** [comment]
Thanks!
